import 'models/coffee.dart';

final Map<String, List<ModelCoffee>> productsData = {
  'ispiresoNapoliCoffee': [
    ModelCoffee(
      id: 01,
      title: 'Ispireso Napoli',
      image: 'https://i.ibb.co/5h4Hsh2/napoli-xx.png',
      aromaticProfile: 'Exceptionally dark & creamy',
      aromaticNotes: 'Intense',
      intensity: 13,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 02,
      title: 'Ispirazione Palermo Kazaar',
      image: 'https://i.ibb.co/PTwXLFk/kazaar-hd-1-1.png',
      aromaticProfile: 'Exceptionally Intense & Syrupy',
      aromaticNotes: 'Intense',
      intensity: 13,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 03,
      title: 'Ispirazione Ristretto Italiano',
      image: 'https://i.ibb.co/whr34B1/ristretto-hd-3.png',
      aromaticProfile: 'Powerful & Contrasting',
      aromaticNotes: 'Intense',
      intensity: 13,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 04,
      title: 'Ispirazione Ristretto Decaffeinato',
      image: 'https://i.ibb.co/crG5Zx5/nespresso-2-1-1.png',
      aromaticProfile: 'Powerful & Contrasting',
      aromaticNotes: 'Intense',
      intensity: 13,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 05,
      title: 'Ispirazione Firenze Arpeggio',
      image: 'https://i.ibb.co/9ZqbcBv/arpeggio-hd-3.png',
      aromaticProfile: 'Intense & Creamy',
      aromaticNotes: 'Intense',
      intensity: 9,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 06,
      title: 'Ispirazione Firenze Arpeggio Decaffeinato',
      image:
          'https://i.ibb.co/pn2qRG8/arpeggio-decaffeinato-hd-new-look-1-1.png',
      aromaticProfile: 'Intense & Creamy',
      aromaticNotes: 'Intense',
      intensity: 9,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 07,
      title: 'Ispirazione Venezia',
      image: 'https://i.ibb.co/BrCvtfD/venezia-xx.png',
      aromaticProfile: 'Exceptionally dark & creamy',
      aromaticNotes: 'Harmoniously balanced & thick body',
      intensity: 9,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 08,
      title: 'Ispirazione Roma',
      image: 'https://i.ibb.co/yyBbdz1/roma-hd-2.png',
      aromaticProfile: 'Exceptionally dark & creamy',
      aromaticNotes: 'Intense',
      intensity: 8,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 09,
      title: 'Ispirazione Genova Livanto',
      image: 'https://i.ibb.co/gWtQzQp/livanto-hd-1.png',
      aromaticProfile: 'Exceptionally dark & creamy',
      aromaticNotes: 'Round & Intense',
      intensity: 6,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
  ],
  'masterOriginCoffee': [
    ModelCoffee(
      id: 10,
      title: 'India',
      image: 'https://i.ibb.co/mzLTW6B/7712-3.png',
      aromaticProfile: 'Intense And Spicy',
      aromaticNotes: 'Balanced',
      intensity: 11,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 11,
      title: 'Indonesia',
      image: 'https://i.ibb.co/ZJZsKqw/7711-3.png',
      aromaticProfile: 'Rich And Woody',
      aromaticNotes: 'Balanced',
      intensity: 8,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 12,
      title: 'Colombia',
      image: 'https://i.ibb.co/1nkBRfS/7715-3.png',
      aromaticProfile: 'Fruity And Vibrant',
      aromaticNotes: 'Balanced',
      intensity: 6,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 13,
      title: 'Nicaragua',
      image: 'https://i.ibb.co/R748nn8/7713-3.png',
      aromaticProfile: 'Sweet And Harmonious',
      aromaticNotes: 'Balanced',
      intensity: 5,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
    ModelCoffee(
      id: 14,
      title: 'Ethiopia',
      image: 'https://i.ibb.co/F0Fc4NC/7714-3.png',
      aromaticProfile: 'Flowery And Bright',
      aromaticNotes: 'Balanced',
      intensity: 4,
      acidity: 5,
      bitterness: 1,
      body: 4,
      roasting: 3,
    ),
  ],
};

// final List<ModelCoffee> productsData = [
//   ModelCoffee(
//     id: 01,
//     title: 'Ispireso Napoli',
//     image: 'https://i.ibb.co/5h4Hsh2/napoli-xx.png',
//     aromaticProfile: 'Exceptionally dark & creamy',
//     aromaticNotes: 'Intense',
//     intensity: 13,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 02,
//     title: 'Ispirazione Palermo Kazaar',
//     image: 'https://i.ibb.co/PTwXLFk/kazaar-hd-1-1.png',
//     aromaticProfile: 'Exceptionally Intense & Syrupy',
//     aromaticNotes: 'Intense',
//     intensity: 13,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 03,
//     title: 'Ispirazione Ristretto Italiano',
//     image: 'https://i.ibb.co/whr34B1/ristretto-hd-3.png',
//     aromaticProfile: 'Powerful & Contrasting',
//     aromaticNotes: 'Intense',
//     intensity: 13,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 04,
//     title: 'Ispirazione Ristretto Decaffeinato',
//     image: 'https://i.ibb.co/crG5Zx5/nespresso-2-1-1.png',
//     aromaticProfile: 'Powerful & Contrasting',
//     aromaticNotes: 'Intense',
//     intensity: 13,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 05,
//     title: 'Ispirazione Firenze Arpeggio',
//     image: 'https://i.ibb.co/9ZqbcBv/arpeggio-hd-3.png',
//     aromaticProfile: 'Intense & Creamy',
//     aromaticNotes: 'Intense',
//     intensity: 9,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 06,
//     title: 'Ispirazione Firenze Arpeggio Decaffeinato',
//     image: 'https://i.ibb.co/pn2qRG8/arpeggio-decaffeinato-hd-new-look-1-1.png',
//     aromaticProfile: 'Intense & Creamy',
//     aromaticNotes: 'Intense',
//     intensity: 9,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 07,
//     title: 'Ispirazione Venezia',
//     image: 'https://i.ibb.co/BrCvtfD/venezia-xx.png',
//     aromaticProfile: 'Exceptionally dark & creamy',
//     aromaticNotes: 'Harmoniously balanced & thick body',
//     intensity: 9,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 08,
//     title: 'Ispirazione Roma',
//     image: 'https://i.ibb.co/yyBbdz1/roma-hd-2.png',
//     aromaticProfile: 'Exceptionally dark & creamy',
//     aromaticNotes: 'Intense',
//     intensity: 8,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 09,
//     title: 'Ispirazione Genova Livanto',
//     image: 'https://i.ibb.co/gWtQzQp/livanto-hd-1.png',
//     aromaticProfile: 'Exceptionally dark & creamy',
//     aromaticNotes: 'Round & Intense',
//     intensity: 6,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
// ];

// final List<ModelCoffee> productsData2 = [
//   ModelCoffee(
//     id: 10,
//     title: 'India',
//     image: 'https://i.ibb.co/mzLTW6B/7712-3.png',
//     aromaticProfile: 'Intense And Spicy',
//     aromaticNotes: 'Balanced',
//     intensity: 11,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 11,
//     title: 'Indonesia',
//     image: 'https://i.ibb.co/ZJZsKqw/7711-3.png',
//     aromaticProfile: 'Rich And Woody',
//     aromaticNotes: 'Balanced',
//     intensity: 8,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 12,
//     title: 'Colombia',
//     image: 'https://i.ibb.co/1nkBRfS/7715-3.png',
//     aromaticProfile: 'Fruity And Vibrant',
//     aromaticNotes: 'Balanced',
//     intensity: 6,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 13,
//     title: 'Nicaragua',
//     image: 'https://i.ibb.co/R748nn8/7713-3.png',
//     aromaticProfile: 'Sweet And Harmonious',
//     aromaticNotes: 'Balanced',
//     intensity: 5,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
//   ModelCoffee(
//     id: 14,
//     title: 'Ethiopia',
//     image: 'https://i.ibb.co/F0Fc4NC/7714-3.png',
//     aromaticProfile: 'Flowery And Bright',
//     aromaticNotes: 'Balanced',
//     intensity: 4,
//     acidity: 5,
//     bitterness: 1,
//     body: 4,
//     roasting: 3,
//   ),
// ];
